<a href="https://colab.research.google.com/github/GuptaNavdeep1983/CS688/blob/main/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install gym

In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v0")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
num_episodes = 100000
max_steps_per_episode = 1000

learning_rate = 0.01
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [42]:
rewards_all_episodes = []
for episode in range(num_episodes):
  state = env.reset()
  done = False
  rewards_current_episode = 0
  for step in range(max_steps_per_episode):
    exploration_rate_random = random.uniform(0, 1)
    # decide on what action (exploitation/exploration)
    if (exploration_rate_random > exploration_rate):
      action = np.argmax(q_table[state, :])
    else:
      action = env.action_space.sample()
    # take next action
    new_state, reward, done, info = env.step(action)
    # calculate the cumulative reward for this action based on previous rewards
    q_table[state, action] = ((1 - learning_rate) * q_table[state, action]) + \
                        (learning_rate * (reward + discount_rate * np.max(q_table[new_state, :])))

    state = new_state
    rewards_current_episode += reward 

    if done:
      break;

  # Exploration rate decay
  exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
  learning_rate = 
  if (episode % 1000 == 0):
    print("exploration_rate: %f"% (exploration_rate))

  rewards_all_episodes.append(rewards_current_episode)

exploration_rate: 1.000000
exploration_rate: 0.374201
exploration_rate: 0.143982
exploration_rate: 0.059289
exploration_rate: 0.028132
exploration_rate: 0.016671
exploration_rate: 0.012454
exploration_rate: 0.010903
exploration_rate: 0.010332
exploration_rate: 0.010122
exploration_rate: 0.010045
exploration_rate: 0.010017
exploration_rate: 0.010006
exploration_rate: 0.010002
exploration_rate: 0.010001
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
exploration_rate: 0.010000
e

In [43]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.05100000000000004
2000 :  0.21800000000000017
3000 :  0.4280000000000003
4000 :  0.5940000000000004
5000 :  0.6730000000000005
6000 :  0.6590000000000005
7000 :  0.6780000000000005
8000 :  0.6880000000000005
9000 :  0.7000000000000005
10000 :  0.6940000000000005
11000 :  0.7120000000000005
12000 :  0.6940000000000005
13000 :  0.6880000000000005
14000 :  0.6830000000000005
15000 :  0.7160000000000005
16000 :  0.7130000000000005
17000 :  0.6960000000000005
18000 :  0.6780000000000005
19000 :  0.6770000000000005
20000 :  0.6470000000000005
21000 :  0.6910000000000005
22000 :  0.7230000000000005
23000 :  0.7000000000000005
24000 :  0.7060000000000005
25000 :  0.7150000000000005
26000 :  0.7010000000000005
27000 :  0.7180000000000005
28000 :  0.6610000000000005
29000 :  0.6870000000000005
30000 :  0.6960000000000005
31000 :  0.6760000000000005
32000 :  0.7150000000000005
33000 :  0.6860000000000005
34000 :  0.6920000000000005
3

In [46]:
print(q_table)
np.exp(-exploration_decay_rate*10000)

[[0.53267317 0.52162734 0.52187916 0.52042261]
 [0.36729765 0.33508407 0.33049259 0.48961676]
 [0.44742024 0.43260552 0.42769357 0.46602841]
 [0.3171366  0.29856497 0.30863683 0.45371854]
 [0.54948448 0.37955835 0.40163945 0.40201585]
 [0.         0.         0.         0.        ]
 [0.36667477 0.22477512 0.29716721 0.15031508]
 [0.         0.         0.         0.        ]
 [0.38144572 0.38885271 0.38531031 0.58418705]
 [0.44905863 0.65019282 0.50572231 0.34566507]
 [0.61639283 0.51838388 0.37071892 0.32945738]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45002323 0.47011525 0.75183903 0.47259276]
 [0.74553306 0.86324522 0.82963559 0.76565568]
 [0.         0.         0.         0.        ]]


4.5399929762484854e-05